echo '<!DOCTYPE html>'
echo '<html>'
echo '  <head>'
echo '    <meta charset="utf-8">'
echo '    <title>OpenIPC camera</title>'
echo '  </head>'
echo '  <body>'
echo '    <form>'
echo '      <table border="0">'
echo '<!--                        system                      -->'
           logLevel=`yaml-cli -g .system.logLevel`
       sensorConfig=`yaml-cli -g .system.sensorConfig`
    sensorConfigDir=`yaml-cli -g .system.sensorConfigDir`
            webPort=`yaml-cli -g .system.webPort`
          staticDir=`yaml-cli -g .system.staticDir`
          httpsPort=`yaml-cli -g .system.httpsPort`
   httpsCertificate=`yaml-cli -g .system.httpsCertificate`
httpsCertificateKey=`yaml-cli -g .system.httpsCertificateKey`
      updateChannel=`yaml-cli -g .system.updateChannel`
             buffer=`yaml-cli -g .system.buffer`
echo '        <tr>'
echo '          <td align="right">system</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>logLevel</td>'
echo '          <td>'
echo '            <select autocomplete="off" name="logLevel">'
echo -n '              <option '; [ "${logLevel}" == "ERROR" ] && echo -n 'selected '; echo ' value="ERROR">ERROR</option>'
echo -n '              <option '; [ "${logLevel}" == "WARN"  ] && echo -n 'selected '; echo ' value="WARN">WARN</option>'
echo -n '              <option '; [ "${logLevel}" == "INFO"  ] && echo -n 'selected '; echo ' value="DEBUG">INFO</option>'
echo -n '              <option '; [ "${logLevel}" == "DEBUG" ] && echo -n 'selected '; echo ' value="DEBUG">DEBUG</option>'
echo -n '              <option '; [ "${logLevel}" == "TRACE" ] && echo -n 'selected '; echo ' value="TRACE">TRACE</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr title="set the value to hardcode sensor configuration, otherwise'
echo 'it will be inferred from SENSOR environment variable">'
echo '          <td>sensorConfig</td>'
echo '          <td><input placeholder="/etc/sensors/imx222_1080p_line.ini" name="sensorConfig" value="'${sensorConfig}'"></td>'
echo '        </tr>'
echo '        <tr title="set custom directory for sensor configs">'
echo '          <td>sensorConfigDir</td>'
echo '          <td><input placeholder="/etc/sensors" name="sensorConfigDir" value="'${sensorConfigDir}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>webPort</td>'
echo '          <td><input placeholder="80" name="webPort" value="'${webPort}'"></td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>staticDir</td>'
echo '          <td><input placeholder="/var/www/html" name="staticDir" value="'${staticDir}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>httpsPort</td>'
echo '          <td><input placeholder="443" name="httpsPort" value="'${httpsPort}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>httpsCertificate</td>'
echo '          <td><input placeholder="/etc/ssl/certs/www.example.com.crt" name="httpsCertificate" value="'${httpsCertificate}'"></td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>httpsCertificateKey</td>'
echo '          <td><input placeholder="/etc/ssl/private/www.example.com.key" name="httpsCertificateKey" value="'${httpsCertificateKey}'"></td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>updateChannel</td>'
echo '          <td>'
echo '            <select name="updateChannel">'
echo -n '              <option '; [ "${updateChannel}" == "testing" ] && echo -n 'selected '; echo ' value="testing">testing</option>'
echo -n '              <option '; [ "${updateChannel}" == "beta" ]    && echo -n 'selected '; echo ' value="beta">beta</option>'
echo -n '              <option '; [ "${updateChannel}" == "stable" ]  && echo -n 'selected '; echo ' value="stable">stable</option>'
echo -n '              <option '; [ "${updateChannel}" == "none" ]    && echo -n 'selected '; echo ' value="none">none</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>  '
echo '        <tr title="maximum buffer size of each client in Kbytes">'
echo '          <td>buffer</td>'
echo '          <td><input placeholder="1024" name="buffer" value="'${buffer}'"></td>'
echo '        </tr>'
echo '<!--                        isp                      -->        '
        memMode=`yaml-cli -g .isp.memMode`
    slowShutter=`yaml-cli -g .isp.slowShutter`
    antiFlicker=`yaml-cli -g .isp.antiFlicker`
     alignWidth=`yaml-cli -g .isp.alignWidth`
         blkCnt=`yaml-cli -g .isp.blkCnt`
threadStackSize=`yaml-cli -g .isp.threadStackSize`
            drc=`yaml-cli -g .isp.drc`
echo '        <tr>        '
echo '          <td align="right">isp</td>'
echo '        </tr>        '
echo '        <tr>'
echo '          <td>memMode</td>'
echo '          <td>'
echo '            <select name="memMode">'
echo -n '              <option '; [ "${memMode}" == "normal" ]    && echo -n 'selected '; echo ' value="normal">normal</option>'
echo -n '              <option '; [ "${memMode}" == "reduction" ] && echo -n 'selected '; echo ' value="reduction">reduction</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>  '
echo '        <tr title="Automatic frame rate reduction mode (slow shutter mode)">'
echo '          <td>slowShutter</td>'
echo '          <td>'
echo '            <select autocomplete="off" name="slowShutter">'
echo -n '              <option '; [ "${slowShutter}" == "disabled" ] && echo -n 'selected '; echo 'value="disabled">disabled</option>'
echo -n '              <option '; [ "${slowShutter}" == "low" ]      && echo -n 'selected '; echo 'value="low">low</option>'
echo -n '              <option '; [ "${slowShutter}" == "medium" ]   && echo -n 'selected '; echo 'value="medium">medium</option>'
echo -n '              <option '; [ "${slowShutter}" == "high" ]     && echo -n 'selected '; echo 'value="high">high</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>  '
echo '        <tr title="use 50 or 60 for indoor camera depending on your location">'
echo '          <td>antiFlicker</td>'
echo '          <td>'
echo '            <select name="antiFlicker">'
echo -n '              <option '; [ "${antiFlicker}" == "disabled" ] && echo -n 'selected '; echo ' value="disabled">disabled</option>'
echo -n '              <option '; [ "${antiFlicker}" == "50" ]       && echo -n 'selected '; echo ' value="50">50</option>'
echo -n '              <option '; [ "${antiFlicker}" == "60" ]       && echo -n 'selected '; echo ' value="60">60</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>alignWidth</td>'
echo '          <td><input placeholder="8" name="alignWidth" value="'${alignWidth}'"></td>'
echo '        </tr>  '
echo '        <tr title="4 for small memory systems and 10 and more for performant SoCs">'
echo '          <td>blkCnt</td>'
echo '          <td><input placeholder="4" name="blkCnt" value="'${blkCnt}'"></td>'
echo '        </tr>  '
echo '        <tr title="in Kbytes">'
echo '          <td>threadStackSize</td>'
echo '          <td><input placeholder="16" name="threadStackSize value="'${threadStackSize}'""></td>'
echo '        </tr>  '
echo '        <tr title="Used to implement dynamic range compression">'
echo '          <td>drc</td>'
echo '          <td><input placeholder="300" name="drc" value="'${drc}'"></td>'
echo '        </tr>'
echo '<!--                        image                      -->        '
    mirror=`yaml-cli -g .image.mirror`
      flip=`yaml-cli -g .image.flip`
    rotate=`yaml-cli -g .image.rotate`
  contrast=`yaml-cli -g .image.contrast`
       hue=`yaml-cli -g .image.hue`
saturation=`yaml-cli -g .image.saturation`
 luminance=`yaml-cli -g .image.luminance`
echo '        <tr>'
echo '          <td align="right">image</td>'
echo '        </tr>        '
echo '        <tr>'
echo '          <td>mirror</td>'
echo '          <td>'
echo '            <select name="mirror">'
echo -n '              <option '; [ "${mirror}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${mirror}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>  '
echo '        <tr title="turn image upside down">'
echo '          <td>flip</td>'
echo '          <td>'
echo '            <select name="flip">'
echo -n '              <option '; [ "${flip}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${flip}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>  '
echo '        <tr title="rotate image by none, 90 or 270 degrees">'
echo '          <td>rotate</td>'
echo '          <td>'
echo '            <select name="rotate">'
echo -n '              <option '; [ "${rotate}" == "none" ] && echo -n 'selected '; echo ' value="none">none</option>'
echo -n '              <option '; [ "${rotate}" == "90" ]   && echo -n 'selected '; echo ' value="90">90</option>'
echo -n '              <option '; [ "${rotate}" == "270" ]  && echo -n 'selected '; echo ' value="270">270</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>  '
echo '        <tr title="auto or 1-99 (50)">'
echo '          <td>contrast</td>'
echo '          <td><input placeholder="auto" name="contrast" value="'${contrast}'"></td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>hue</td>'
echo '          <td><input placeholder="50" name="hue" value="'${hue}'"></td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>saturation</td>'
echo '          <td><input placeholder="50" name="saturation" value="'${saturation}'"></td>'
echo '        </tr>  '
echo '        <tr title="auto or 1-99 (50)">'
echo '          <td>luminance</td>'
echo '          <td><input placeholder="auto" name="luminance" value="'${luminance}'"></td>'
echo '        </tr> '
echo '<!--                        osd                      -->        '
osd_enabled=`yaml-cli -g .osd.enabled`
       font=`yaml-cli -g .osd.font`
   template=`yaml-cli -g .osd.template`
       posX=`yaml-cli -g .osd.posX`
       posY=`yaml-cli -g .osd.posY`
echo '        <tr>  '
echo '          <td align="right">osd</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="osd_enabled">'
echo -n '              <option '; [ "${osd_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${osd_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>font</td>'
echo '          <td><input placeholder="/usr/lib/fonts/fonts.bin" name="font" value="'${font}'"></td>'
echo '        </tr>'
echo '        <tr title="add '%f' to show milliseconds (consumes more resources)">'
echo '          <td>template</td>'
echo '          <td><input placeholder="%a %e %B %Y %H:%M:%S %Z" name="template" value="'${template}'"></td>'
echo '        </tr>  '
echo '        <tr title="positive values count from left and top '
echo 'negative ones from right and bottom">'
echo '          <td>posX</td>'
echo '          <td><input placeholder="-100" name="posX" value="'${posX}'"></td>'
echo '        </tr>'
echo '        <tr title="positive values count from left and top '
echo 'negative ones from right and bottom">'
echo '          <td>posY</td>'
echo '          <td><input placeholder="-100" name="posY" value="'${posY}'"></td>'
echo '        </tr>'
echo '<!--                        nightMode                      -->        '
nightMode_enabled=`yaml-cli -g .nightMode.enabled`
      irSensorPin=`yaml-cli -g .nightMode.irSensorPin`
irSensorPinInvert=`yaml-cli -g .nightMode.irSensorPinInvert`
        irCutPin1=`yaml-cli -g .nightMode.irCutPin1`
        irCutPin2=`yaml-cli -g .nightMode.irCutPin2`
 pinSwitchDelayUs=`yaml-cli -g .nightMode.pinSwitchDelayUs`
     backlightPin=`yaml-cli -g .nightMode.backlightPin`
         nightAPI=`yaml-cli -g .nightMode.nightAPI`
      drcOverride=`yaml-cli -g .nightMode.drcOverride`
echo '        <tr>  '
echo '          <td align="right">nightMode</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="nightMode_enabled">'
echo -n '              <option '; [ "${nightMode_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${nightMode_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>irSensorPin</td>'
echo '          <td><input placeholder="62" name="irSensorPin" value="'${irSensorPin}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>irSensorPinInvert</td>'
echo '          <td>'
echo '            <select name="irSensorPinInvert">'
echo -n '              <option '; [ "${irSensorPinInvert}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${irSensorPinInvert}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>irCutPin1</td>'
echo '          <td><input placeholder="1" name="irCutPin1" value="'${irCutPin1}'"></td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>irCutPin2</td>'
echo '          <td><input placeholder="2" name="irCutPin2" value="'${irCutPin2}'"></td>'
echo '        </tr>'
echo '        <tr title="switch delay in us on IRcut filter pins. WARNING!'
echo 'a very long delay can damage the IRcut filter!!!">'
echo '          <td>pinSwitchDelayUs</td>'
echo '          <td><input placeholder="150" name="pinSwitchDelayUs" value="'${pinSwitchDelayUs}'"></td>'
echo '        </tr>'
echo '        <tr title="turn on backlight illumination when night mode is on">'
echo '          <td>backlightPin</td>'
echo '          <td><input placeholder="65" name="backlightPin" value="'${backlightPin}'"></td>'
echo '        </tr>  '
echo '        <tr title="use /night/{invert,on,off} endpoints to change mode by API for remote callers">'
echo '          <td>nightAPI</td>'
echo '          <td>'
echo '            <select name="nightAPI">'
echo -n '              <option '; [ "${nightAPI}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${nightAPI}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr title="use special value for drc parameter in night mode">'
echo '          <td>drcOverride</td>'
echo '          <td><input placeholder="300" name="drcOverride" value="'${drcOverride}'"></td>'
echo '        </tr>'
echo '<!--                        records                      -->        '
records_enabled=`yaml-cli -g .records.enabled`
           path=`yaml-cli -g .records.path`
       maxUsage=`yaml-cli -g .records.maxUsage`
echo '        <tr>  '
echo '          <td align="right">records</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="records_enabled">'
echo -n '              <option '; [ "${records_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${records_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>path</td>'
echo '          <td><input placeholder="/mnt/mmc/%Y/%m/%d/%H.mp4" name="path" value="'${path}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>maxUsage</td>'
echo '          <td><input placeholder="95" name="maxUsage" value="'${maxUsage}'"></td>'
echo '        </tr>  '
echo '<!--                        video0                      -->'
video0_enabled=`yaml-cli -g .video0.enabled`
  video0_codec=`yaml-cli -g .video0.codec`
   video0_size=`yaml-cli -g .video0.size`
    video0_fps=`yaml-cli -g .video0.fps`
video0_bitrate=`yaml-cli -g .video0.bitrate`
       gopSize=`yaml-cli -g .video0.gopSize`
       gopMode=`yaml-cli -g .video0.gopMode`
        rcMode=`yaml-cli -g .video0.rcMode`
          crop=`yaml-cli -g .video0.crop`
echo '        <tr>'
echo '          <td align="right">video0</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="video0_enabled">'
echo -n '              <option '; [ "${video0_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${video0_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>codec</td>'
echo '          <td>'
echo '            <select name="video0_codec">'
echo -n '              <option '; [ "${video0_codec}" == "h265" ] && echo -n 'selected '; echo ' value="h265">h265</option>'
echo -n '              <option '; [ "${video0_codec}" == "h264" ] && echo -n 'selected '; echo ' value="h264">h264</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>size</td>'
echo '          <td><input placeholder="1920x1080" name="video0_size" value="'${video0_size}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>fps</td>'
echo '          <td><input placeholder="25" name="video0_fps" value="'${video0_fps}'"></td>'
echo '        </tr>'
echo '        <tr title="Kbits per second">'
echo '          <td>bitrate</td>'
echo '          <td><input placeholder="4096" name="video0_bitrate" value="'${video0_bitrate}'"></td>'
echo '        </tr>  '
echo '        <tr title="send I-frame each 1 second">'
echo '          <td>gopSize</td>'
echo '          <td><input placeholder="1" name="gopSize" value="'${gopSize}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>gopMode</td>'
echo '          <td>'
echo '            <select name="gopMode">'
echo -n '              <option '; [ "${gopMode}" == "normal" ] && echo -n 'selected '; echo ' value="normal">normal</option>'
echo -n '              <option '; [ "${gopMode}" == "dual" ]   && echo -n 'selected '; echo ' value="dual">dual</option>'
echo -n '              <option '; [ "${gopMode}" == "smart" ]  && echo -n 'selected '; echo ' value="smart">smart</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>rcMode</td>'
echo '          <td>'
echo '            <select name="rcMode">'
echo -n '              <option '; [ "${rcMode}" == "avbr" ] && echo -n 'selected '; echo ' value="avbr">avbr</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>crop</td>'
echo '          <td><input placeholder="0x0x960x540" name="crop" value="'${crop}'"></td>'
echo '        </tr>'
echo '<!--                        video1                      -->'
video1_enabled=`yaml-cli -g .video1.enabled`
  video1_codec=`yaml-cli -g .video1.codec`
   video1_size=`yaml-cli -g .video1.size`
    video1_fps=`yaml-cli -g .video1.fps`
# video1_bitrate=`yaml-cli -g .video1.bitrate`
#       gopSize=`yaml-cli -g .video1.gopSize`
#       gopMode=`yaml-cli -g .video1.gopMode`
#        rcMode=`yaml-cli -g .video1.rcMode`
#          crop=`yaml-cli -g .video1.crop`
echo '        <tr>'
echo '          <td align="right">video1</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="video1_enabled">'
echo -n '              <option '; [ "${video1_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${video1_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>codec</td>'
echo '          <td>'
echo '            <select name="video1_codec">'
echo -n '              <option '; [ "${video1_codec}" == "h265" ] && echo -n 'selected '; echo ' value="h265">h265</option>'
echo -n '              <option '; [ "${video1_codec}" == "h264" ] && echo -n 'selected '; echo ' value="h264">h264</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>size</td>'
echo '          <td><input placeholder="704x576" name="video1_size" value="'${video1_size}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>fps</td>'
echo '          <td><input placeholder="15" name="video1_fps" value="'${video1_fps}'"></td>'
echo '        </tr>'
echo '<!--                        jpeg                      -->'
 jpeg_enabled=`yaml-cli -g .jpeg.enabled`
    jpeg_size=`yaml-cli -g .jpeg.size`
      qfactor=`yaml-cli -g .jpeg.qfactor`
toProgressive=`yaml-cli -g .jpeg.toProgressive`
echo '        <tr>'
echo '          <td align="right">jpeg</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="jpeg_enabled">'
echo -n '              <option '; [ "${jpeg_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${jpeg_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>size</td>'
echo '          <td><input placeholder="1920x1080" name="jpeg_size" value="'${jpeg_size}'"></td>'
echo '        </tr>'
echo '        <tr title="[1..99] jpeg quality">'
echo '          <td>qfactor</td>'
echo '          <td><input placeholder="50" name="qfactor" value="'${qfactor}'"></td>'
echo '        </tr>'
echo '        <tr title="make additional step to transform snapshot to Progressive JPEG">'
echo '          <td>toProgressive</td>'
echo '          <td>'
echo '            <select name="toProgressive">'
echo -n '              <option '; [ "${toProgressive}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${toProgressive}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '<!--                        mjpeg                      -->'
   mjpeg_size=`yaml-cli -g .mjpeg.size`
    mjpeg_fps=`yaml-cli -g .mjpeg.fps`
mjpeg_bitrate=`yaml-cli -g .mjpeg.bitrate`
echo '        <tr>'
echo '          <td align="right">mjpeg</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>size</td>'
echo '          <td><input placeholder="640x360" name="mjpeg_size" value="'${mjpeg_size}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>fps</td>'
echo '          <td><input placeholder="5" name="mjpeg_fps" value="'${mjpeg_fps}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>bitrate</td>'
echo '          <td><input placeholder="1024" name="mjpeg_bitrate" value="'${mjpeg_bitrate}'"></td>'
echo '        </tr>  '
echo '<!--                        audio                      -->'
audio_enabled=`yaml-cli -g .audio.enabled`
  volume=`yaml-cli -g .audio.volume`
   srate=`yaml-cli -g .audio.srate`
    audio_codec=`yaml-cli -g .audio.codec`
outputEnabled=`yaml-cli -g .audio.outputEnabled`
echo '        <tr>'
echo '          <td align="right">audio</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="audio_enabled">'
echo -n '              <option '; [ "${audio_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${audio_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>volume</td>'
echo '          <td><input placeholder="auto" name="volume" value="'${volume}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>srate</td>'
echo '          <td><input placeholder="8000" name="srate" value="'${srate}'"></td>'
echo '        </tr>  '
echo '        <tr title="select default codec for RTSP and MP4 encoding">  '
echo '          <td>codec</td>'
echo '          <td>'
echo '            <select name="audio_codec">'
echo -n '              <option '; [ "${audio_codec}" == "aac" ]  && echo -n 'selected '; echo ' value="aac">mp3</option>'
echo -n '              <option '; [ "${audio_codec}" == "mp3" ]  && echo -n 'selected '; echo ' value="mp3">opus</option>'
echo -n '              <option '; [ "${audio_codec}" == "opus" ] && echo -n 'selected '; echo ' value="opus">aac</option>'
echo -n '              <option '; [ "${audio_codec}" == "pcm" ]  && echo -n 'selected '; echo ' value="pcm">pcm</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>outputEnabled</td>'
echo '          <td>'
echo '            <select name="outputEnabled">'
echo -n '              <option '; [ "${outputEnabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${outputEnabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '<!--                        rtsp                      -->'
rtsp_enabled=`yaml-cli -g .rtsp.enabled`
   rtsp_port=`yaml-cli -g .rtsp.rport`
echo '        <tr>'
echo '          <td align="right">rtsp</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="rtsp_enabled">'
echo -n '              <option '; [ "${rtsp_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${rtsp_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>port</td>'
echo '          <td><input placeholder="554" name="rtsp_port" value="'${rtsp_port}'"></td>'
echo '        </tr>'
echo '<!--                        hls                      -->'
hls_enabled=`yaml-cli -g .hls.enabled`
echo '        <tr>'
echo '          <td align="right">hls</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="hls_enabled">'
echo -n '              <option '; [ "${hls_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${hls_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '<!--                        youtube                      -->'
youtube_enabled=`yaml-cli -g .youtube.enabled`
key=`yaml-cli -g .youtube.enabled`
echo '        <tr>'
echo '          <td align="right">youtube</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="youtube_enabled">'
echo -n '              <option '; [ "${youtube_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${youtube_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>key</td>'
echo '          <td><input placeholder="xxxx-xxxx-xxxx-xxxx-xxxx" name="key" value="'${key}'"></td>'
echo '        </tr>'
echo '<!--                        motionDetect                      -->'
motionDetect_enabled=`yaml-cli -g .motionDetect.enabled`
             profile=`yaml-cli -g .motionDetect.profile`
           visualize=`yaml-cli -g .motionDetect.visualize`
               debug=`yaml-cli -g .motionDetect.debug`
         constraints=`yaml-cli -g .motionDetect.constraints`
echo '        <tr>'
echo '          <td align="right">motionDetect</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="motionDetect_enabled">'
echo -n '              <option '; [ "${motionDetect_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${motionDetect_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>profile</td>'
echo '          <td>'
echo '            <select name="profile">'
echo -n '              <option '; [ "${profile}" == "outdoor" ] && echo -n 'selected '; echo ' value="outdoor">outdoor</option>'
echo -n '              <option '; [ "${profile}" == "indoor" ]  && echo -n 'selected '; echo ' value="indoor">indoor</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>visualize</td>'
echo '          <td>'
echo '            <select name="visualize">'
echo -n '              <option '; [ "${visualize}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${visualize}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>debug</td>'
echo '          <td>'
echo '            <select name="debug">'
echo -n '              <option '; [ "${debug}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${debug}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr title="ROI for motion detection algorithm'
echo 'e.g. top upper quadrant">'
echo '          <td>constraints</td>'
echo '          <td><input placeholder="0x0x1296x760" name="constraints" value="'${constraints}'"></td>'
echo '        </tr>'
echo '<!--                        ipeye                      -->'
ipeye_enabled=`yaml-cli -g .ipeye.enabled`
echo '        <tr>'
echo '          <td align="right">ipeye</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="ipeye_enabled">'
echo -n '              <option '; [ "${ipeye_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${ipeye_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '<!--                        netip                      -->'
netip_enabled=`yaml-cli -g .netip.enabled`
         user=`yaml-cli -g .netip.user`
     password=`yaml-cli -g .netip.password`
   netip_port=`yaml-cli -g .netip.port`
    snapshots=`yaml-cli -g .netip.snapshots`
echo '        <tr>'
echo '          <td align="right">netip</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="netip_enabled">'
echo -n '              <option '; [ "${netip_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${netip_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>user</td>'
echo '          <td><input placeholder="admin" name="user" value="'${user}'"></td>'
echo '        </tr>'
echo '        <tr title="12345 password">'
echo '          <td>password</td>'
echo '          <td><input placeholder="6V0Y4HLF" name="password" value="'${password}'"></td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>port</td>'
echo '          <td><input placeholder="34567" name="netip_port" value="'${netip_port}'"></td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>snapshots</td>'
echo '          <td>'
echo '            <select name="snapshots">'
echo -n '              <option '; [ "${snapshots}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${snapshots}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '<!--                        onvif                      -->'
onvif_enabled=`yaml-cli -g .onvif.enabled`
echo '        <tr>'
echo '          <td align="right">onvif</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="onvif_enabled">'
echo -n '              <option '; [ "${onvif_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${onvif_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '<!--                        raw                      -->'
raw_mode=`yaml-cli -g .raw.enabled`
echo '        <tr>'
echo '          <td align="right">raw</td>'
echo '        </tr>  '
echo '        <tr title="slow (no more than 1 snapshot at a time)'
echo 'fast (supports snapshot series)">'
echo '          <td>mode</td>'
echo '          <td>'
echo '            <select name="raw_mode">'
echo -n '              <option '; [ "${raw_mode}" == "none" ] && echo -n 'selected '; echo ' value="none">slow</option>'
echo -n '              <option '; [ "${raw_mode}" == "slow" ] && echo -n 'selected '; echo ' value="slow">fast</option>'
echo -n '              <option '; [ "${raw_mode}" == "fast" ] && echo -n 'selected '; echo ' value="fast">none</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '<!--                        watchdog                      -->'
watchdog_enabled=`yaml-cli -g .watchdog.enabled`
         timeout=`yaml-cli -g .watchdog.timeout`
echo '        <tr>'
echo '          <td align="right">watchdog</td>'
echo '        </tr>  '
echo '        <tr>'
echo '          <td>enabled</td>'
echo '          <td>'
echo '            <select name="watchdog_enabled">'
echo -n '              <option '; [ "${watchdog_enabled}" == "false" ] && echo -n 'selected '; echo ' value="false">false</option>'
echo -n '              <option '; [ "${watchdog_enabled}" == "true" ]  && echo -n 'selected '; echo ' value="true">true</option>'
echo '            </select>'
echo '           </td>'
echo '        </tr>'
echo '        <tr>'
echo '          <td>timeout</td>'
echo '          <td><input placeholder="10" name="timeout" value="'${timeout}'"></td>'
echo '        </tr>'
echo '<!--                        submit                      -->'
echo '        <td></td>'
echo '        <td><input type="submit" value="Save" '
echo '        formaction="yaml.htsh" formmethod="post"></td>'
echo '      </table>'
echo '    </form>'
echo '  </body>'
echo '</html>