#!/bin/sh

## N.B. $1 -> Name of .htsh script
##		$2 -> Arguments sent by server to script
tmpfile="/tmp/tss.tmp"
echo 'eval "$1"' >"$tmpfile" # Makes Environmental variables available

flag=0
lc=0
txt=''
while read -r line;do
	let lc=lc+1
	# Start and end tags in same line
	echo "$line"| grep -qe "<?.*?>"  -qe "<?sh.*?>"
	if [ $? -eq 0 ];then
		if [ $flag -eq 0 ];then
			line=${line//<?sh/<?}
			pre=`echo -e "$line" |  sed -e 's/<?.*//'`
			comm=`echo -e "$line" | sed -e 's/^.*<? //' | sed -e 's/?>.*//'`
			post=`echo -e "$line" | sed -e 's/^.*?>//'`
			
			if [ -n "$pre" ];then
				pre=${pre//\\/\\\\}
				mod_pre=`echo -e "$pre" | sed "s/'/\\\'/g" | sed 's/"/\\\"/g'`
				mod_pre=${mod_pre//\$/\\$}
				echo -e "echo  \"$mod_pre\"" >>"$tmpfile"
			fi
			echo -e "$comm" >> "$tmpfile"
			if [ -n "$post" ];then
				post=${post//\\/\\\\}
				mod_post=`echo -e "$post" | sed "s/'/\\\'/g" | sed 's/"/\\\"/g'`
				mod_post=${mod_post//\$/\\$}
				echo -e "echo  \"$mod_post\"" >>"$tmpfile"
			fi
			continue
		else
			echo -e "\n\n<br/><br/>  ERROR : Non-terminated &lt;?sh or &lt;? in file $1 (Line $lc) "
			exit 1
		fi	
	fi
	# Start tag
	echo "$line" | sed 's/^ *//'| grep -q "^<?sh\|^<?"
	if [ $? -eq 0 ];then
		if [ $flag -eq 0 ];then
			flag=1
			line=${line/<?sh}
			echo -e "${line/<?}" >> "$tmpfile"
		else
			echo -e "\n\n<br/><br/>  ERROR : Non-terminated &lt;?sh or &lt;? in file $1 (Line $lc) "
			exit 1
		fi
		continue;
	fi
	# End tag
	echo "$line"|grep -q "?>$"
	if [ $? -eq 0 ];then
		if [ $flag -eq 1 ];then
			flag=0
			echo -e"${line/?>}" >> "$tmpfile"
		else
			echo -e "\n\n<br/><br/>  ERROR : Unmatched ?&gt; in file $1 (Line $lc) "
			exit 1
		fi
		continue;
	fi
	# Take action on current line based on flag
	if [ $flag -eq 0 ];then
		line=${line//\\/\\\\}
		modline=`echo  "$line" |sed "s/'/\\\'/g" | sed 's/"/\\\"/g'`
		modline=${modline//\$/\\$}
		echo -e "echo  \"$modline\"" >>"$tmpfile"
	else
		echo -e "${line}" >> "$tmpfile"
	fi
done < "$1"

/bin/sh "$tmpfile" "$2"
rm -f "$tmpfile"
exit 0
