#!/bin/sh

MOTION_ARGS=""
MOTION_PID_FILE=/var/run/motiondetection.pid

start() {
  printf "Starting motion detection: "
  umask 077
  start-stop-daemon -S -q -p $MOTION_PID_FILE \
    --exec /usr/sbin/motiondetection.sh -- $MOTION_ARGS
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
  printf "Stopping motion detection: "
  start-stop-daemon -K -q -p $MOTION_PID_FILE
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart | reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $?
