#!/bin/sh
#
# if [ $(grep savedumps /etc/coredump.config | cut -d= -f2) == "true" ]; then
#   ulimit -c unlimited && echo /root/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
# fi
#

conf_file=/etc/coredump.config
core_file=*.core
info_file=info.txt                                                                     

if [ ! -f "$conf_file" ]; then
  echo "Config file $conf_file not found."
  exit 1
fi

if [ ! "$(grep savedumps $conf_file | cut -d= -f2)" == "true" ]; then
  echo "Core dump not enabled."
  exit 2
fi

cd /tmp
mv /root/${core_file} /tmp/ 2>/dev/null
if [ $? -ne 0 ]; then
  echo "No core dump found. Exiting."
  return 3
fi

bundle_name=$(ifconfig -a | grep HWaddr | sed s/.*HWaddr// | sed "s/[: ]//g" | uniq)-$(date +"%Y%m%d-%H%M%S").tgz

name=$(grep contact_name $conf_file | cut -d= -f2)
email=$(grep contact_email $conf_file | cut -d= -f2)
telegram=$(grep contact_telegram $conf_file | cut -d= -f2)
soc=$(ipcinfo --chip-name)
family=$(ipcinfo --family)
vendor=$(ipcinfo --vendor)
sensor=$(ipcinfo --long_sensor)
mac=$(ipcinfo --xm-mac)
os=$(cat /etc/os-release)
mj=$(majestic -v)

:>$info_file
echo -e "Date: $(TZ=GMT date)\nName: $name\nEmail: $email\nTelegram: $telegram\n" >> $info_file
echo -e "Hardware:\n---------\nSoC: $soc\nFamily: $family\nVendor: $vendor\nSensor: $sensor\nMAC: $mac\n" >> $info_file
echo -e "Firmware:\n---------\n$os\nMAJESTIC_VERSION=\"$mj\"\n" >> $info_file

cat /etc/majestic.yaml > majestic.yaml

tar c -h $core_file $info_file majestic.yaml | gzip > $bundle_name

if [ "$(grep send2tftp $conf_file | cut -d= -f2)" == "true" ]; then
  tftphost=$(grep tftphost $conf_file | cut -d= -f2)
  tftp -p -l $bundle_name $tftphost
fi

if [ "$(grep send2devs $conf_file | cut -d= -f2)" == "true" ]; then
  curl -v https://majdumps.s3.eu-north-1.amazonaws.com/$bundle_name --upload-file /tmp/$bundle_name
fi

rm $bundle_name $core_file $info_file majestic.yaml

exit 0
