<%
# line format: parameter|type
mj="
.system.logLevel|select
.system.webAdmin|boolean
.system.staticDir|string
.system.webPort|number
.system.httpsPort|number
.system.httpsCertificate|string
.system.httpsCertificateKey|string
.system.updateChannel|select
.system.buffer|number
.isp.sensorConfig|string
.isp.memMode|select
.isp.slowShutter|select
.isp.antiFlicker|select
.isp.blkCnt|number
.isp.exposure|range
.isp.aGain|number
.isp.dGain|number
.isp.ispGain|number
.isp.drc|number
.isp.lowDelay|boolean
.isp.rawMode|select
.isp.iqProfile|string
.image.mirror|boolean
.image.flip|boolean
.image.rotate|select
.image.contrast|range
.image.hue|range
.image.saturation|range
.image.luminance|range
.osd.enabled|boolean
.osd.font|string
.osd.template|string
.osd.posX|number
.osd.posY|number
.osd.privacyMasks|string
.nightMode.enabled|boolean
.nightMode.irSensorPin|number
.nightMode.irSensorPinInvert|boolean
.nightMode.irCutPin1|number
.nightMode.irCutPin2|number
.nightMode.pinSwitchDelayUs|number
.nightMode.backlightPin|number
.nightMode.drcOverride|number
.records.enabled|boolean
.records.path|string
.records.maxUsage|range
.video0.enabled|boolean
.video0.codec|select
.video0.size|string
.video0.fps|number
.video0.bitrate|number
.video0.gopSize|number
.video0.gopMode|select
.video0.rcMode|select
.video0.crop|string
.video0.sliceUnits|number
.video1.enabled|boolean
.video1.codec|select
.video1.size|string
.video1.fps|number
.video1.bitrate|number
.video1.gopSize|number
.video1.gopMode|select
.video1.rcMode|select
.video1.crop|string
.video1.sliceUnits|number
.jpeg.enabled|boolean
.jpeg.size|string
.jpeg.qfactor|range
.jpeg.toProgressive|boolean
.mjpeg.size|string
.mjpeg.fps|number
.mjpeg.bitrate|number
.audio.enabled|boolean
.audio.volume|range
.audio.srate|number
.audio.codec|select
.audio.device|string
.audio.outputEnabled|boolean
.rtsp.enabled|boolean
.rtsp.port|number
.hls.enabled|boolean
.youtube.enabled|boolean
.youtube.key|string
.motionDetect.enabled|boolean
.motionDetect.profile|select
.motionDetect.visualize|boolean
.motionDetect.debug|boolean
.motionDetect.constraints|string
.ipeye.enabled|boolean
.netip.enabled|boolean
.netip.user|string
.netip.password_plain|string
.netip.password|hidden
.netip.port|number
.netip.snapshots|boolean
.netip.ignoreSetTime|boolean
.onvif.enabled|boolean
.watchdog.enabled|boolean
.watchdog.timeout|number
.cloud.enabled|boolean
"
%>
