<%
# line format: parameter|units|type|o,p,t,i,o,n,s|placeholder|hint
mj="
.system.logLevel||select|ERROR,WARN,INFO,DEBUG,TRACE|TRACE|
.system.staticDir||string||/var/www/html|
.system.webPort||number|1-65535|80|
.system.httpsPort||number|1-65535|443|
.system.httpsCertificate||string||/etc/ssl/certs/www.example.com.crt|
.system.httpsCertificateKey||string||/etc/ssl/private/www.example.com.key|
.system.updateChannel||select|testing,beta,stable,none|stable|
.system.buffer|KB|number||1024|
.isp.memMode||select|normal,reduction|reduction|
.isp.sensorConfig||string||/etc/sensors/imx222_1080p_line.ini|
.isp.slowShutter||select|disabled,low,medium,high|low|Automatic frame rate reduction mode.
.isp.antiFlicker||select|disabled,50Hz,60Hz|disabled|Usually, the utility frequency in your grid line.
.isp.alignWidth||number||8|
.isp.blkCnt||number|1-32|4|Use 4 for small memory systems, 10+ for performant SoCs.
.isp.threadStackSize|KB|number|1-32|16|
.isp.exposure|&micro;s|range|auto,1-500000|auto|From 1 to 500000.
.isp.aGain||number|0.1-1.0|1|
.isp.dGain||number|0.1-1.0|1|
.isp.ispGain||number|0.1-1.0|1|
.isp.drc|:1|number|1-1000|300|
.isp.rawMode||select|slow,fast,none|slow|
.image.mirror||boolean|true,false|false|
.image.flip||boolean|true,false|false|
.image.rotate||select|0°,90°,270°|0|
.image.contrast|%|range|auto,1-100|auto|
.image.hue|%|range|1-100|50|
.image.saturation|%|range|1-100|50|
.image.luminance|%|range|auto,1-100|auto|
.osd.enabled||boolean|true,false|false|
.osd.font||string||/usr/share/fonts/truetype/UbuntuMono-Regular.ttf|
.osd.template||string||%a %e %B %Y %H:%M:%S %Z|Supports strftime() format.
.osd.posX|px|number|-2000-2000|-100|
.osd.posY|px|number|-2000-2000|-100|
.osd.privacyMasks|px|string||0x0x234x640,2124x0x468x1300|Coordinates of masked areas separated by commas.
.nightMode.enabled||boolean|true,false|false|
.nightMode.irSensorPin||number|1-100|62|
.nightMode.irSensorPinInvert||boolean|true,false|false|
.nightMode.irCutPin1||number|1-100|1|
.nightMode.irCutPin2||number|1-100|2|
.nightMode.pinSwitchDelayUs||number|0-1000|150|
.nightMode.backlightPin||number|1-100|65|
.nightMode.drcOverride||number|1-1000|300|
.records.enabled||boolean|true,false|false|
.records.path||string||/mnt/mmc/%Y/%m/%d/%H.mp4|Supports strftime() format.
.records.maxUsage|%|range|1-100|95|
.video0.enabled||boolean|true,false|true|
.video0.codec||select|h264,h265|h264|
.video0.size|px|string|1920x1080,1280x720,704x576|1920x1080|
.video0.fps|fps|number|1-60|25|
.video0.bitrate|kbps|number|1-4096|4096|
.video0.gopSize||number|1-20|1|
.video0.gopMode||select|normal,dual,smart|normal|
.video0.rcMode||select|avbr|avbr|
.video0.crop|px|string||0x0x960x540|
.video1.enabled||boolean|true,false|false|
.video1.codec||select|h264,h265|h264|
.video1.size|px|string|1920x1080,1280x720,704x576|704x576|
.video1.fps|fps|number|1-60|15|
.video1.bitrate|kbps|number|1-4096|2048|
.video1.gopSize||number|1-20|1|
.video1.gopMode||select|normal,dual,smart|normal|
.video1.rcMode||select|avbr|avbr|
.video1.crop|px|string||0x0x960x540|
.jpeg.enabled||boolean|true,false|true|
.jpeg.size|px|string||1920x1080||
.jpeg.qfactor|%|range|1-100|50|
.jpeg.toProgressive||boolean|true,false|false|
.mjpeg.size|px|string||640x360|
.mjpeg.fps|fps|number|1-30|5|
.mjpeg.bitrate|kbps|number|1-4096|1024|
.audio.enabled||boolean|true,false|false|
.audio.volume|%|range|auto,1-100|auto|
.audio.srate|kHz|number|1-44100|8000|
.audio.codec||select|mp3,opus,pcm,alaw,ulaw|opus|
.audio.outputEnabled||string||hw:3|
.rtsp.enabled||boolean|true,false|true||
.rtsp.user||string||admin|
.rtsp.password-plain||string||12345|
.rtsp.password||hidden||12345|
.rtsp.port||number|1-65535|554|rtsp://[ip.add.re.ss]:[port]/stream={0,1}
.hls.enabled||boolean|true,false|true|
.youtube.enabled||boolean|true,false|false|
.youtube.key||string||xxxx-xxxx-xxxx-xxxx-xxxx|
.motionDetect.enabled||boolean|true,false|false|
.motionDetect.profile||select|outdoor,indoor|outdoor|
.motionDetect.visualize||boolean|true,false|true|
.motionDetect.debug||boolean|true,false|true|
.motionDetect.constraints|px|string||0x0x1296x760|
.ipeye.enabled||boolean|true,false|false|
.netip.enabled||boolean|true,false|false|
.netip.user||string||admin|
.netip.password-plain||string||12345|
.netip.password||hidden||6V0Y4HLF|
.netip.port||number|1-65535|34567|
.netip.snapshots||boolean|true,false|true|
.netip.ignoreSetTime||boolean|true,false|false|
.onvif.enabled||boolean|true,false|false|
.watchdog.enabled||boolean|true,false|true|
.watchdog.timeout|sec|number|1-1000|10|
.cloud.enabled||boolean|true,false|false|
"
%>
