#!/bin/sh

if [ -z "$(cat /etc/mtab | grep /tmp/www)" ]
then
  mkdir -p /tmp/www
  mount -t nfs -o nolock,tcp 192.168.1.61:/home/paul/localwork/microbe-web/files/var/www /tmp/www
fi

# shellcheck disable=SC2009
pid=$(ps ax | grep httpd | grep 86 | xargs | cut -d " " -f 1)
[ -n "$pid" ] && kill -9 "$pid"
sleep 3
HTTP_MODE=development httpd -p 86 -h "/tmp/www" -c /dev/null
